version: '3.4'

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      'MYSQL_DATABASE': 'itmotive'
      'MYSQL_ROOT_PASSWORD': 'itmotive'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:6
    ports:
      - "6379:6379"
